name: Keepalive

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'
        required: false
        default: 'Manual trigger'
  schedule:
    - cron:  "0 0 * * *"

permissions:
  contents: write

jobs:

  keepalive:
    name: Keepalive
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: keepalive

      # ensures that crons are not suspended after 60 days
      - name: Keepalive check
        uses: gautamkrishnar/keepalive-workflow@v1
        with:
          use_api: true
          gh_token: ${{ secrets.INVENIOBOT_PAT }}
